services:
  - type: web
    name: cardioprep-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: USE_AUTH
        value: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: PORT
        value: 10000
